### ISSUE TITLE
Need to handle error: Error creating post with long title

### ISSUE THREAD

**Issue by llibdude** [planetscale/flux#224]
I tried to create a post with this title: `This is a phat title. Like the phatest. It goes on for days and days and never seems to stop. Is there an end to this madness? Some say there isn't. But should there be? Some say there should be. Certainly we'll hit the database limit? What are we, varchar(255)? More? I guess we'll find out. Threads only allows for 60 chars, and they have a nifty indicator of chars remaining that counts down. I don't hate that. Okay this is clearly long enough if it still goes through then we can say this is too long.  For the record this title is 552 characters.`

The subtitle and content were short, tho I assume the same applied to the subtitle (we should check it).

When trying to create the post, the `post` endpoint returns with this response
```
{
   "error":{
      "code":"P2000",
      "clientVersion":"2.13.0",
      "meta":{
         "column_name":"code"
      }
   }
}
```

**Comment by raunaqgupta** [comment]
There is now a limit on title length.
