### ISSUE TITLE
Links break posts

### ISSUE THREAD

**Issue by llibdude** [planetscale/flux#304]
Reported on a post in prod https://flux.psdb.co/post/18

If a post contains a url of the format `<https://github.com/planetscale/project-big-bang/issues/28>` the post breaks with error
`RangeError: No value supplied for attribute href`

I have also noticed if I paste a raw url into the post `https://github.com/planetscale/project-big-bang/issues/28` it instantly breaks with error:
`serializer.js?9636:251 Uncaught TypeError: value is not a function`

I presume this is all directly related to new markdown library that is being used.

**Comment by raunaqgupta** [comment]
Closing this issue as it was fixed by removing the `mention` prosemirror feature which will now be dealt with independently.
