### ISSUE TITLE
Images don't work?

### ISSUE THREAD

**Issue by lizztheblizz** [planetscale/flux#418]
Was playing around with Flux and wanted to post a picture of my pizza (2.2mb JPEG) in post 73, but was deeply troubled to find it shows up as a broken link.

<img width="807" alt="Screenshot 2021-03-14 at 18 40 32" src="https://user-images.githubusercontent.com/310564/111080301-bb59a380-84f5-11eb-85c2-d7efbfb204f2.png">

May be related to #409 ?

**Comment by raunaqgupta** [comment]
TODO: run migration to change Image column type from `blob` to `mediumblob`

**Comment by raunaqgupta** [comment]
Should be resolved by #461
